services:
  dotnet-sdk:
    container_name: dotnetsdk
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command:
      - /bin/sh
      - -c
      - |
        dotnet add package Microsoft.Data.SqlClient
        dotnet run
        tail -f /dev/null 
    working_dir: /app
    volumes:
      - ./:/app
